apiVersion: v1
kind: Service
metadata:
  name: quantified-self-api
  labels:
    app: authenticator
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 3090
      protocol: TCP
  selector:
    app: authenticator
  type: ClusterIP