apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qsapi
  name: qsapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qsapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qsapi
    spec:
      containers:
        - image: ammanvedi/selfequalsthis:qsapi_v2.0.1
          imagePullPolicy: IfNotPresent
          name: quantified-self-api
          ports:
            - containerPort: 3090
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: myregistrykey
