apiVersion: v1
kind: Service
metadata:
  name: authenticator
  labels:
    app: authenticator
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: authenticator
  type: ClusterIP